name: "Wazuh Agent"
description: "Wazuh Agent add-on for Home Assistant: enrolls an agent and forwards logs/events to a Wazuh Manager ."
version: "1.1.2" # x-release-please-version
slug: "wazuh_agent"

init: false
startup: services

arch:
  - amd64
  - aarch64

# Allow read-only access to the host journal.
journald: true

options:
  manager_address: ""
  agent_name: "home-assistant"
  agent_group: ""
  enrollment_port: 1515
  communication_port: 1514
  enrollment_key: ""
  force_reenroll: false
  security_profile: "minimal"
  debug_dump_config: false

schema:
  manager_address: str
  agent_name: str
  agent_group: str?
  enrollment_port: int
  communication_port: int
  enrollment_key: password?
  force_reenroll: bool
  security_profile: list(minimal|standard)
  debug_dump_config: bool

map:
  - type: homeassistant_config
    read_only: true
    path: /config
