name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@v2
        with:
          scandir: "./wazuh-agent"

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "./wazuh-agent/Dockerfile"

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: amd64
            platform: linux/amd64
            build_from: ghcr.io/home-assistant/amd64-base-debian:bookworm
          - architecture: aarch64
            platform: linux/arm64
            build_from: ghcr.io/home-assistant/aarch64-base-debian:bookworm
          - architecture: armv7
            platform: linux/arm/v7
            build_from: ghcr.io/home-assistant/armv7-base-debian:bookworm

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.architecture }}
        uses: docker/build-push-action@v6
        with:
          context: ./wazuh-agent
          file: ./wazuh-agent/Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          build-args: |
            BUILD_FROM=${{ matrix.build_from }}
